### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by funjoker** [Nullsig/SkillCalc#2]
https://gist.github.com/funjoker/03b4ef6574b590dc43fc92c73680a64e

Hint: maybe you can add some design part to it.
2. Hint: on WQHD Screens the Site looks a bit different.
3. Hint: english texts are outdated

**Comment by Nullsig** [comment]
Sorry for the delay on pushing these, the holidays had me busy. Thank you so much for the work!

**Comment by funjoker** [comment]
You're welcome.

**Comment by funjoker** [comment]
What about using the files from LiF directly?
The texts are selected by id in locale files. Might be a universal solution for every translation

**Comment by Nullsig** [comment]
I honestly wasn't aware that they were accessible. I pulled the icons from
the LiF files but never knew the text was available. Not sure if some of
the other hard text values would work.

Eventually I wanted to put more information in the stat block too once
people find more information in how they affect damage and speed.

**Comment by funjoker** [comment]
This are the ids inside cm_messages.xml

EN: ...\Life is Feudal Your Own\data
Others: ...\Life is Feudal Your Own\data\loc\ **LANGUAGE_SHORTCUT** \data

| displayName| allText| zeroText| thirtyText| sixtyText| ninetyText| hundredText |
| --------- | ------------ | --------- | --------- | ----------- | --------- | ----------- |
| Advanced Farming | 286| 287 | 288 | 289| 290 | 291 |
| Alchemy| 184| 185 | 186 | 187| 188 | 189 |
| Animal lore| 226| 227 | 228 | 229| 230 | 231 |
| Architecture | 214| 215 | 216 | 217| 218 | 219 |
| Armorsmithing| 124| 125 | 126 | 127| 128 | 129 |
| Artisan| 100| 101 | 102 | 103| 104 | 105 |
| Arts | 412| 413 | 414 | 415| 416 | 417 |
| Authority| 484| 485 | 486 | 487| 488 | 489 |
| Battle Survival| 442| 443 | 444 | 445| 446 | 447 |
| Blades mastery | 310| 311 | 312 | 313| 314 | 315 |
| Bowcraft | 148| 149 | 150 | 151| 152 | 153 |
| Bows mastery | 388| 389 | 390 | 391| 392 | 393 |
| Brewing| 172| 173 | 174 | 175| 176 | 177 |
| Building Maintain| 136| 137 | 138 | 139| 140 | 141 |
| Carpentry| 142| 143 | 144 | 145| 146 | 147 |
| Chainmail armors | 256| 257 | 258 | 259| 260 | 261 |
| Chivalry | 328| 329 | 330 | 331| 332 | 333 |
| Combat preparation | 394| 395 | 396 | 397| 398 | 399 |
| Construction | 202| 203 | 204 | 205| 206 | 207 |
| Cooking| 238| 239 | 240 | 241| 242 | 243 |
| Crossbows mastery| 382| 383 | 384 | 385| 386 | 387 |
| Demolition | 448| 449 | 450 | 451| 452 | 453 |
| Digging| 190| 191 | 192 | 193| 194 | 195 |
| Drill| 454| 455 | 456 | 457| 458 | 459 |
| Equipment maintain | 436| 437 | 438 | 439| 440 | 441 |
| Farming| 220| 221 | 222 | 223| 224 | 225 |
| Forestry | 130| 131 | 132 | 133| 134 | 135 |
| Forging| 118| 119 | 120 | 121| 122 | 123 |
| General actions| 466| 467 | 468 | 469| 470 | 471 |
| Healing| 178| 179 | 180 | 181| 182 | 183 |
| Heavy horse handling | 274| 275 | 276 | 277| 278 | 279 |
| Herbalism| 166| 167 | 168 | 169| 170 | 171 |
| Horseback riding | 472| 473 | 474 | 475| 476 | 477 |
| Hunting| 400| 401 | 402 | 403| 404 | 405 |
| Jewelry| 406| 407 | 408 | 409| 410 | 411 |
| Lancing| 268| 269 | 270 | 271| 272 | 273 |
| Masonry| 208| 209 | 210 | 211| 212 | 213 |
| Materials Preparation| 196| 197 | 198 | 199| 200 | 201 |
| Mentoring| 424| 425 | 426 | 427| 428 | 429 |
| Mining | 106| 107 | 108 | 109| 110 | 111 |
| Mounted fighting mastery | 262| 263 | 264 | 265| 266 | 267 |
| Movement | 460| 461 | 462 | 463| 464 | 465 |
| Nature's Lore| 160| 161 | 162 | 163| 164 | 165 |
| Piercing mastery | 334| 335 | 336 | 337| 338 | 339 |
| Piety| 418| 419 | 420 | 421| 422 | 423 |
| Plate armors | 346| 347 | 348 | 349| 350 | 351 |
| Poleaxes mastery | 304| 305 | 306 | 307| 308 | 309 |
| Precious Prospecting | 280| 281 | 282 | 283| 284 | 285 |
| Procuration| 232| 233 | 234 | 235| 236 | 237 |
| Scale armors | 316| 317 | 318 | 319| 320 | 321 |
| Shield mastery | 322| 323 | 324 | 325| 326 | 327 |
| Smelting | 112| 113 | 114 | 115| 116 | 117 |
| Spear mastery| 292| 293 | 294 | 295| 296 | 297 |
| Swimming | 478| 479 | 480 | 481| 482 | 483 |
| Tailoring| 244| 245 | 246 | 247| 248 | 249 |
| Two-handed Axes Mastery| 352| 353 | 354 | 355| 356 | 357 |
| Two-handed Blades Mastery| 340| 341 | 342 | 343| 344 | 345 |
| Two-handed Blunt Mastery | 358| 359 | 360 | 361| 362 | 363 |
| Unit and formation | 430| 431 | 432 | 433| 434 | 435 |
| War cries| 364| 365 | 366 | 367| 368 | 369 |
| Warfare engineering| 154| 155 | 156 | 157| 158 | 159 |
| Warhorse training| 250| 251 | 252 | 253| 254 | 255 |
| Warrior| 298| 299 | 300 | 301| 302 | 303 |


The combinations of the ids and the skills is inside skill_types.xml (...\Life is Feudal Your Own\data).

```
        <ID>1</ID>
        <Name>Artisan</Name>
        <Parent>0</Parent>
        <Group>1</Group>
        <PrimaryStat>Int</PrimaryStat>
        <SecondaryStat>Str</SecondaryStat>
        <Icon>art\2D\skills\Artisan.png</Icon>
        <UnknownIcon>art\2D\skills\Artisan_u.png</UnknownIcon>
        <Passive>100</Passive>
        <DescLvl0>101</DescLvl0>
        <DescLvl30>102</DescLvl30>
        <DescLvl60>103</DescLvl60>
        <DescLvl90>104</DescLvl90>
        <DescLvl100>105</DescLvl100>
        <MasterMessageID>594</MasterMessageID>
        <GMMessageID>595</GMMessageID>
```

The name translation of skill name is inside skill_types.xml  ( ...\Life is Feudal Your Own\data\loc\ **LANGUAGE_SHORTCUT** \data)

**Comment by funjoker** [comment]
I will check if i can find Id's for your hardtext describtion there too (i think they are there too)

**Comment by funjoker** [comment]
Is implemented.
